name: tuto-ci-docker
"on":
  push:
    branches:
      - main
      - develop
jobs:
  job1:
    build: null
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Node.js 20
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Run the tests
      run: npm test --coverage
job2:
  needs: job1
  build:
    name: Build Docker image
    runs-on: "${{ matrix.os }}"
    strategy: null
    matrix:
      os:
        - ubuntu-latest
        - ubuntu-20.04
      node-version:
        - 19.x
        - 20.x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with: null
        context: .
        file: ./Dockerfile
        push: true
        tags: >-
          ${{ secrets.DOCKERHUB_USERNAME }}/ci-js-docker:latest-${{
          github.ref_name }}-${{ matrix.os }}-nodev${{ matrix.node-version }}
